name: CI

on: [push]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node and npm
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint
